---
spring:
  application.name: authorization-app
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization-db
    username: authorization
    password: authorization
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
app:
  jwt:
    secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    token-expiration: P3M
